"""create tables in PostgreSQL

Revision ID: d1a89618e995
Revises: e5ef7159f1ce
Create Date: 2024-09-19 15:17:39.885685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a89618e995'
down_revision: Union[str, None] = 'e5ef7159f1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
